server:
  servlet:
    context-path: /
    session:
      timeout: 60m
  port: 8040

spring:
  security:
    user:
      name: user
      password: 1234

  profiles:
    active: local
#    active: dev
    #active: release

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # in 쿼리의 갯수 (데이터가 1000 개 가 있을 경우 10번 쿼리가 나간다)

    database-platform: org.hibernate.dialect.MariaDB103Dialect

  data:
    web:
      pageable:
        default-page-size: 10

  servlet:
    multipart:
      location: /file-upload/base-proj-boot/upload
      maxFileSize: 100MB
      maxRequestSize: 150MB

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.springframework.boot.autoconfigure: ERROR

common:
  javascript:
    version: 231221
  aes:
    key: ieetuWebSocket!@

decorator:
  datasource:
    p6spy:
      enable-logging: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


--- # profile : local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.231:5432/baseproj?characterEncoding=UTF-8&allowMultiQueries=true
    username: baseproj
    password: 12fnxmfoq!@

--- # profile : dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.231:3306/baseproj?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: MNjW9vqC

--- # profile : release
spring:
  config:
    activate:
      on-profile: release
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.231:5432/
    username:
    password: